<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>TextWork.Plugins.WordReplacePlugin</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\TextWork.Core\TextWork.Core.csproj" />
    </ItemGroup>

</Project>
