<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\MostUsedWordsPlugin\MostUsedWordsPlugin.csproj" />
    <ProjectReference Include="..\TextWork.Plugins.ParagraphCountPlugin\TextWork.Plugins.ParagraphCountPlugin.csproj" />
    <ProjectReference Include="..\TextWork.Core\TextWork.Core.csproj" />
    <ProjectReference Include="..\TextWork.Plugin.SymbolCount\TextWork.Plugins.SymbolCount.csproj" />
    <ProjectReference Include="..\TextWork.Plugins.AverageWordLength\TextWork.Plugins.AverageWordLength.csproj" />
    <ProjectReference Include="..\TextWork.Plugins.LongestWord\TextWork.Plugins.LongestWord.csproj" />
    <ProjectReference Include="..\TextWork.Plugins.TestPlugins\TextWork.Plugins.TestPlugins.csproj" />
    <ProjectReference Include="..\TextWork.Plugins.UniqueWords\TextWork.Plugins.UniqueWords.csproj" />
  </ItemGroup>

</Project>
